### ISSUE TITLE
swaggers for all API

### ISSUE THREAD

**Issue by oneku16** [UCADevClub/HIS-back#20]
need to write a swagger for all API, You can user patient views-swagger as a template. if you need to change some fields in serializers do it.

**Comment by oneku16** [comment]
How is your progress@muz2002 ? Do you need help?

**Comment by muz2002** [comment]
> How is your progress@muz2002 ? Do you need help?



> How is your progress@muz2002 ? Do you need help?
I will do it later today or tomorrow

**Comment by oneku16** [comment]
well done, @muz2002, пока у нас нет заданий, можем отдыхать. Скоро новый спринт начнется, там будет много чего. Можешь посмтотреть googl calendar API или же Outlook, будем работать с букингом.
